### ISSUE TITLE
Outline bug in `न्क`

### ISSUE THREAD

**Issue by davelab6** [TypeNetwork/Poppins#2]
A user reported a small outline/interpolation bug in Poppins as found in GF today, which is old, found in all styles.

Text is `न्क`

![Screenshot 2020-07-08 at 6 59 20 PM](https://user-images.githubusercontent.com/261579/86935891-55698080-c10b-11ea-9fe2-4b96f9c26135.png)

Is this fixed in the upcoming TN VF release?

**Comment by moyogo** [comment]
Fixed in prepare-vf branch.
<img width="193" alt="image" src="https://user-images.githubusercontent.com/1923747/104602011-d97c6200-5672-11eb-8e35-9a26f80a2bfb.png">
