### ISSUE TITLE
Accent position /dvCH_R 

### ISSUE THREAD

**Issue by pichotta** [TypeNetwork/Poppins#3]
@moyogo 

Could you check out this accent position in **/dvCH_R** in the **Regular** ?  
Also, Issue #2  Thanks!

![Poppins Regular :dvCH_R ](https://user-images.githubusercontent.com/6576107/104482963-90a2ab80-5595-11eb-9d16-726d2e1d2245.png)

**Comment by moyogo** [comment]
Fixed in prepare-vf branch

**Comment by moyogo** [comment]
<img width="337" alt="image" src="https://user-images.githubusercontent.com/1923747/104601847-a0dc8880-5672-11eb-81e5-99ee312d720a.png">
